<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Regression Test</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>2c16af78-60ba-4b27-a492-b85b43d8fbf7</testSuiteGuid>
   <testCaseLink>
      <guid>1fd9609c-8152-4ba1-98d3-17b366e12374</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Get list user</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04f9377a-6ebc-448d-99e3-b918de983163</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a719bf0-0f41-4854-b7df-a8aa24800efb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>24430e72-669d-4d6e-baf3-da009341e126</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Get single user</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>37b25c2e-bfd5-4c2a-a9f6-6254a2678888</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6332201e-834f-40d3-b9e3-c520d2d9f55c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Update user</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db9349fe-1d3b-4be2-858e-1eb23bb9ebcf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f16cdb8-a82a-40cc-b79b-efdf994134d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66bdf730-b319-4d17-8b97-284344641c9a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ace6bfaa-58c2-409b-8bc2-5012cc411afe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Register</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8af95ba7-4493-412d-a7d1-84655ce5d43e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03115234-dcb2-4089-8ddf-87a446617208</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
